### ISSUE TITLE
Add object group option to relevant commands and client methods

### ISSUE THREAD

**Issue by maheshlokhande1** [IBM/lmctl#178]
Add objectgroup optional parameter to create requests using LMCTL for following objects where changes are needed

 assembly Create a Assembly
 assemblyconfig Create a Assembly Configuration
 behaviourproject Create a Behaviour Project
 deploymentlocation Create a Deployment Location
 descriptor Create a Descriptor
 descriptortemplate Create a Descriptor Template
 intent Request an intent of any type on an Assembly
 resourcepkg Upload a Resource Package
 scenario Create a Scenario

**Comment by dvaccarosenna** [comment]
# Final implementation

## New option

`--og, --object-group` option and `--ogid, --object-group-id` option added to relevant commands. 

The `--og, --object-group` option accepts the name of an object group. This option is the most convenient however, as the REST APIs expect the ID of an object group, using this option will result in an API call to retrieve the object group with the given name first, in order to determine the ID. 

The `--ogid, --object-group-id` option accepts the ID of an object group and therefore does not result in any additional API calls.

## Supported commands

- `lmctl create assembly`
- `lmctl create behaviourproject`
- `lmctl create deploymentlocation`
- `lmctl create descriptor`
- `lmctl create infrastructurekey`
- `lmctl create intent`
- `lmctl create resourcepkg`
- `lmctl get assembly`
- `lmctl get behaviourproject`
- `lmctl get deploymentlocation`
- `lmctl get descriptor`
- `lmctl get infrastructurekey`
- `lmctl get resourcepkg`
- `lmctl get process`
- `lmctl pkg push`
- `lmctl project push`
- `lmctl project test`
